version: '3'
service:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
            - /app/node_modules
            - ./frontend:/app
    environment:
            - CHOKIDAR_USEPOLLING=true
  api:
    build: ./api 
    ports:
      - '5000:5000'
    volumes:
            - ./api:/app

